In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [57]:
train = pd.read_csv('cs-215-assignment-3-multiple-variate-regression/train.csv')
train.drop(columns=['id', 'Row#'], inplace=True)
print(train.shape)
train

(15000, 17)

,clonesize,honeybee,bumbles,andrena,osmia,MaxOfUpperTRange,MinOfUpperTRange,AverageOfUpperTRange,MaxOfLowerTRange,MinOfLowerTRange,AverageOfLowerTRange,RainingDays,AverageRainingDays,fruitset,fruitmass,seeds,yield
0,25.0,0.50,0.25,0.75,0.63,94.6,57.2,79.0,68.2,33.0,55.9,34.0,0.56,0.402948,0.409261,31.274591,4418.44126
1,12.5,0.25,0.25,0.25,0.25,77.4,46.8,64.7,55.8,27.0,45.8,34.0,0.56,0.500438,0.445494,34.467567,5862.80545
2,25.0,0.50,0.25,0.38,0.75,94.6,57.2,79.0,68.2,33.0,55.9,24.0,0.39,0.509001,0.459421,36.624966,6079.08526
3,12.5,0.25,0.25,0.75,0.75,94.6,57.2,79.0,68.2,33.0,55.9,16.0,0.26,0.583379,0.498056,40.865478,7400.77538
4,12.5,0.25,0.25,0.50,0.63,77.4,46.8,64.7,55.8,27.0,45.8,24.0,0.39,0.447669,0.423764,33.298861,4858.24073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,12.5,0.25,0.25,0.50,0.63,69.7,42.1,58.2,50.2,24.3,41.2,34.0,0.56,0.335927,0.352186,28.793440,3182.69865
14996,12.5,0.25,0.25,0.38,0.63,77.4,46.8,64.7,55.8,27.0,45.8,34.0,0.56,0.545095,0.470719,38.042756,5862.80545
14997,12.5,0.25,0.25,0.75,0.50,77.4,46.8,64.7,55.8,27.0,45.8,16.0,0.26,0.481801,0.442535,35.414082,5569.13925
14998,25.0,0.50,0.38,0.38,0.75,86.0,52.0,71.9,62.0,30.0,50.8,1.0,0.10,0.552359,0.470847,38.625436,6795.88187
14999,12.5,0.25,0.25,0.50,0.75,86.0,52.0,71.9,62.0,30.0,50.8,1.0,0.10,0.523846,0.464067,37.758138,6526.98819

In [63]:
# from fasteda import fast_eda
# fast_eda(train)

In [58]:
test = pd.read_csv('cs-215-assignment-3-multiple-variate-regression/test.csv')
test.drop(columns=['id', 'Row#'], inplace=True)
test

,clonesize,honeybee,bumbles,andrena,osmia,MaxOfUpperTRange,MinOfUpperTRange,AverageOfUpperTRange,MaxOfLowerTRange,MinOfLowerTRange,AverageOfLowerTRange,RainingDays,AverageRainingDays,fruitset,fruitmass,seeds
0,25.0,0.50,0.25,0.38,0.63,77.4,46.8,64.7,55.8,27.0,45.8,24.0,0.39,0.424574,0.417909,31.448420
1,12.5,0.25,0.25,0.63,0.63,69.7,42.1,58.2,50.2,24.3,41.2,16.0,0.26,0.552359,0.476308,38.417394
2,25.0,0.25,0.25,0.25,0.25,69.7,42.1,58.2,50.2,24.3,41.2,24.0,0.39,0.511413,0.445494,35.487008
3,25.0,0.50,0.38,0.38,0.63,86.0,52.0,71.9,62.0,30.0,50.8,24.0,0.39,0.520637,0.460795,37.712513
4,12.5,0.25,0.25,0.38,0.25,94.6,57.2,79.0,68.2,33.0,55.9,16.0,0.26,0.470593,0.438026,35.824852
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,12.5,0.25,0.25,0.38,0.63,86.0,52.0,71.9,62.0,30.0,50.8,16.0,0.26,0.608345,0.509528,42.487539
9996,12.5,0.25,0.25,0.63,0.50,94.6,57.2,79.0,68.2,33.0,55.9,34.0,0.56,0.362184,0.388822,29.370607
9997,25.0,0.50,0.25,0.38,0.63,86.0,52.0,71.9,62.0,30.0,50.8,16.0,0.26,0.589622,0.487428,40.813181
9998,12.5,0.25,0.25,0.38,0.38,94.6,57.2,79.0,68.2,33.0,55.9,16.0,0.26,0.593030,0.494895,41.971816
9999,25.0,0.50,0.38,0.50,0.75,69.7,42.1,58.2,50.2,24.3,41.2,34.0,0.56,0.388956,0.396044,29.388560

In [59]:
# Standardising the data set
def standardise(data):
	# Standardising the data
	data_mean = data.mean()
	data_std = data.std()
	data = (data - data_mean) / data_std
	return data, data_mean, data_std

train, train_mean, train_std = standardise(train.iloc[:, 13:16])

train_Y = train.iloc[:, 16]
print(train_Y)

       fruitset  fruitmass     seeds
0     -1.289173  -0.975560 -1.187064
1     -0.015666  -0.022115 -0.407197
2      0.096203   0.344337  0.119736
3      1.067801   1.360963  1.155457
4     -0.704987  -0.593930 -0.692647
...         ...        ...       ...
14995 -2.164672  -2.477390 -1.793071
14996  0.567692   0.641650  0.466023
14997 -0.259122  -0.099980 -0.176016
14998  0.662594   0.644999  0.608339
14999  0.290115   0.466595  0.396507

[15000 rows x 3 columns]
0        4418.44126
1        5862.80545
2        6079.08526
3        7400.77538
4        4858.24073
            ...
14995    3182.69865
14996    5862.80545
14997    5569.13925
14998    6795.88187
14999    6526.98819
Name: yield, Length: 15000, dtype: float64

In [61]:
def standardise_test(data, mean, std):
    data = (data - mean) / std
    return data

In [38]:
def get_x(i, m, train_set):
    '''returns the x matrix for the polynomial regression'''
    # get the x column
    x = train_set.iloc[:, i].values
    x = x.flatten()
    #get a matrix where the ith row is x^i in numpy
    x = np.array([x**i for i in range(1,m+1)]).T
    # print("x shape: ", x.shape)
    return x

def get_other_x(i, m, train_set):
    '''returns all colums before the ith column in the train set'''
    x = train_set.iloc[:, :i].values

    return x

def get_y(j, train_set):
    '''returns the y column for the polynomial regression'''
    y = train_set.iloc[:, j].values
    # print("y shape: ", y.shape)
    return y

def get_weights(X, Y):
    '''returns the weights for the polynomial regression'''
    return np.linalg.inv(X.T.dot(X)).dot(X.T).dot(Y)

In [39]:
def r2_score(X, Y, B):
    '''returns the r2 score'''
    return 1 - (np.sum((Y - X.dot(B))**2) / np.sum((Y - np.mean(Y))**2))

def ssr(X, Y, B):
    '''returns the sum of squared residuals'''
    return np.sum((Y - X.dot(B))**2)

In [40]:
def k_fold_cross_validation(y, k, train_set, std_train, train_mean, train_std):
    '''returns the k fold cross validation for all degrees'''
    k_fold = {}
    for i in range(1, 20):
        for a in range(1,20):
            for b in range(1,20):
                # print(i,a,b)
                ssr_list = []
                for j in range(k):
                    # get the jth fold
                    # print(j)
                    test = standardise_test(std_train.iloc[j::k, :], train_mean, train_std)
                    train = std_train.drop(std_train.index[j::k])
                    train_X1 = get_x(13, i, std_train)
                    train_X2 = get_x(14, a, std_train)
                    train_X3 = get_x(15, b, std_train)
                    train_Xbefore = get_other_x(13, i, std_train)
                    print(train_Xbefore.shape, train_X1.shape, train_X2.shape, train_X3.shape)
                    # train_X = np.ones((train_X1.shape[0], 1))
                    train_X = np.concatenate((np.ones((train_X1.shape[0], 1)),train_Xbefore, train_X1, train_X2, train_X3), axis=1)
                    # print(train_X)
                    train_Y = get_y(y, train)

                    B = get_weights(train_X, train_Y)


                    test_X1 = get_x(13, i, test)
                    test_X2 = get_x(14, a, test)
                    test_X3 = get_x(15, b, test)
                    test_Xbefore = get_other_x(13, i, test)
                    test_X = np.concatenate((np.ones((test_X1.shape[0], 1)),test_Xbefore, test_X1, test_X2, test_X3), axis=1)
                    test_Y = get_y(y, test)
                    # ssr = np.sum((test_Y - test_X.dot(B))**2)
                    ssr_list.append(ssr(test_X, test_Y, B))

                k_fold[(i, a, b)] = np.mean(ssr_list)
                # print("Degree: ", i, "SSR: ", np.mean(ssr_list))
    return k_fold
k = 2
best_m_dict = k_fold_cross_validation(16, k, train, std_train)

# for i in range(13, 16):
#     print(i)
#     best_m_list.append(np.argmin(k_fold_cross_validation(i, 16, 10, train)))

In [41]:
print(best_m_dict)
best_m = min(best_m_dict, key=best_m_dict.get)
# best_m = [8,3,1]

In [42]:
def get_trainX(train, best_m):
    '''returns the train X matrix'''
    train_X1 = get_x(13, best_m[0], train)
    train_X2 = get_x(14, best_m[1], train)
    train_X3 = get_x(15, best_m[2], train)
    train_Xbefore = get_other_x(13, best_m[0], train)
    train_X = np.concatenate((np.ones((train_X1.shape[0], 1)),train_Xbefore, train_X1, train_X2, train_X3), axis=1)
    return train_X

def get_trainY(train_set):
    '''returns the train Y matrix'''
    return get_y(16, train)

In [43]:
train_X1 = get_trainX(train, best_m)

In [44]:
train_Y1 = get_trainY(train)

In [45]:
# df = pd.DataFrame()
# for i in range(3):
# 	x_train = get_x(best_m_list[0])

In [46]:
def fit(train_x, train_y):
	# Adding a column of ones to the train_x
	# train_x = np.c_[np.ones(train_x.shape[0]), train_x]

	# Calculating the coefficients
	coefficients = np.linalg.inv(train_x.T @ train_x) @ train_x.T @ train_y
	return coefficients

coefficients = fit(train_X1, train_Y1).reshape(-1, 1)
print(coefficients)
print(coefficients.shape)

[[ 2.32956935e+05]
 [-1.91423355e+00]
 [ 3.16355788e+01]
 [ 1.38064064e+02]
 [ 3.49295668e+01]
 [ 5.73601965e+01]
 [ 6.59626683e+03]
 [ 6.14959632e+03]
 [-6.47919840e+02]
 [-8.57719382e+00]
 [-2.79870126e+04]
 [-7.96025216e+00]
 [-1.15227158e+00]
 [-1.68173811e+01]
 [-4.67511019e+06]
 [ 3.91984445e+07]
 [-1.80379777e+08]
 [ 5.00014269e+08]
 [-8.56360184e+08]
 [ 8.86675242e+08]
 [-5.08431232e+08]
 [ 1.23818453e+08]
 [ 7.09629286e+03]
 [-2.83997922e+04]
 [ 2.93829012e+04]
 [ 8.05446859e+01]]
(26, 1)

In [47]:
def standardise_test(test, train_mean, train_std):
	# Standardising the data
	test = (test - train_mean) / train_std
	return test

In [48]:
# test_X = standardise_test(test.iloc[:, 0:16], train_mean, train_std)
# print(test_X)
# test_X = np.c_[np.ones(test_X.shape[0]), test_X]
# print(test_X)

In [49]:
test_X1 = get_trainX(test, best_m)

In [50]:
test_pred = test_X1 @ coefficients

In [51]:
test_pred = pd.DataFrame(test_pred, columns=['yield'])
print(test_pred)

            yield
0     4537.853497
1     7025.926702
2     6246.986849
3     6407.341705
4     5614.065711
...           ...
9995  7764.666344
9996  3654.029140
9997  7403.677014
9998  7587.962045
9999  4092.081232

[10000 rows x 1 columns]

In [52]:
def submit(y_pred):
	test = pd.read_csv('cs-215-assignment-3-multiple-variate-regression/test.csv')
	test.drop(columns=['Row#', 'clonesize', 'honeybee', 'bumbles', 'andrena', 'osmia', 'MinOfUpperTRange', 'MinOfLowerTRange', 'MaxOfUpperTRange', 'MaxOfLowerTRange', 'AverageOfUpperTRange', 'AverageOfLowerTRange', 'RainingDays', 'AverageRainingDays', 'fruitset', 'fruitmass', 'seeds'], inplace=True)
	test['yield'] = y_pred
	return test

In [53]:
submit(test_pred).to_csv('submission.csv', index=False)